const REDUCER = {
	NAME: 'HOUSES',
	FETCH_END_POINT: '',
};

const CATEGORIES = {
	MILES: 'MILES',
	PRICE: 'PRICE',
	BEDROOMS: 'BEDROOMS',
	BEDROOMS_MIN: 'MIN',
	BEDROOMS_MAX: 'MAX',
	TYPE: 'TYPE',
	ADDRESS: 'ADDRESS',
	FILTER: 'FILTER',
	NO_MIN: 'NO MIN',
	NO_MAX: 'NO_MAX',
	PAGE_CHANGE: 'PAGE_CHANGE',
};

const CONTEXT_LIST_HOUSES = {
	ON_SUBMIT: 'ON_SUBMIT',
	ON_PAGE_CHANGE: 'ON_PAGE_CHANGE',
	ON_ARTICLE_SELECTED: 'ON_ARTICLE_SELECTED',
	NO_SELECTION_SO_FAR: 'NO_SELECTION_SO_FAR',
	NO_PRODUCTS_FOR_THE_SELECTION: 'NO_PRODUCTS_FOR_THE_SELECTION',
	PRODUCTS_AVAILABLE: 'PRODUCTS_AVAILABLE',
	NO_PRODUCTS_AVAILABLE: 'NO_PRODUCTS_AVAILABLE',
	ERROR_SERVER: 'PAGE_ERROR_SERVER',
};
const END_POINT_API = {
	LIST: 'list',
};
const NUMBER_OF_PRODUCTS_PER_PAGE = 20;
const DEFAULT_IMAGES = {
	THUMBNAIL: '/asset/image/houses/comingSoon.jpg',
};

export {
	REDUCER,
	NUMBER_OF_PRODUCTS_PER_PAGE,
	CATEGORIES,
	END_POINT_API,
	CONTEXT_LIST_HOUSES,
	DEFAULT_IMAGES,
};
